name: 'sending email when workflow fails'

on:
    workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
        - name: "checkout code"
          uses: actions/checkout@v2

        - name: 'setup python env'
          uses: actions/setup-python@v2
          with:
              python-version: '3.9'
            
        - name: 'install dependencies'
          run: |
              python -m pip install --upgrade pip

        - name: 'send email'
          run: python script.py
          env:
              workflow_name: ${{ github.workflow }}
              SENDERS_EMAIL: ${{ secrets.SENDERS_EMAIL }}
              RECIEVERS_EMAIL: ${{ secrets.RECIEVERS_EMAIL }}
              SENDERS_PASSWORD: ${{ secrets.SENDERS_PASSWORD }}
              repo_name: ${{ github.repository }}
              workflow_run_id: ${{ github.run_id }}
